"""
Protocol risk assessment constants.

Default configurations for common blockchain protocols.
"""

from .schemas import ConsensusMechanism, SettlementFinality

# Consensus mechanism base scores (out of 100)
CONSENSUS_BASE_SCORES: dict[ConsensusMechanism, float] = {
    ConsensusMechanism.POW: 95.0,
    ConsensusMechanism.POS: 85.0,
    ConsensusMechanism.PBFT: 80.0,
    ConsensusMechanism.POH: 75.0,
    ConsensusMechanism.DPOS: 70.0,
    ConsensusMechanism.POA: 50.0,
    ConsensusMechanism.HYBRID: 75.0,
}

# Finality type adjustments
FINALITY_ADJUSTMENTS: dict[SettlementFinality, float] = {
    SettlementFinality.DETERMINISTIC: 10.0,
    SettlementFinality.ECONOMIC: 5.0,
    SettlementFinality.PROBABILISTIC: 0.0,
}

# Default protocol configurations for common chains
PROTOCOL_DEFAULTS: dict[str, dict] = {
    "bitcoin": {
        "consensus": ConsensusMechanism.POW,
        "finality_type": SettlementFinality.PROBABILISTIC,
        "validator_count": 15000,
        "nakamoto_coefficient": 4,
        "top_10_stake_pct": 85.0,
        "finality_time_seconds": 3600,
        "tps_average": 7.0,
        "tps_peak": 10.0,
        "uptime_30d_pct": 99.99,
        "major_incidents_12m": 0,
        "has_bug_bounty": True,
        "audit_count": 50,
        "time_since_last_upgrade_days": 180,
        "total_staked_usd": None,
        "slashing_enabled": False,
    },
    "ethereum": {
        "consensus": ConsensusMechanism.POS,
        "finality_type": SettlementFinality.ECONOMIC,
        "validator_count": 900000,
        "nakamoto_coefficient": 5,
        "top_10_stake_pct": 45.0,
        "finality_time_seconds": 768,
        "tps_average": 15.0,
        "tps_peak": 30.0,
        "uptime_30d_pct": 99.99,
        "major_incidents_12m": 0,
        "has_bug_bounty": True,
        "audit_count": 100,
        "time_since_last_upgrade_days": 60,
        "total_staked_usd": 100_000_000_000,
        "slashing_enabled": True,
    },
    "solana": {
        "consensus": ConsensusMechanism.POH,
        "finality_type": SettlementFinality.DETERMINISTIC,
        "validator_count": 1900,
        "nakamoto_coefficient": 31,
        "top_10_stake_pct": 35.0,
        "finality_time_seconds": 0.4,
        "tps_average": 3000.0,
        "tps_peak": 65000.0,
        "uptime_30d_pct": 99.5,
        "major_incidents_12m": 2,
        "has_bug_bounty": True,
        "audit_count": 20,
        "time_since_last_upgrade_days": 30,
        "total_staked_usd": 50_000_000_000,
        "slashing_enabled": True,
    },
    "polygon": {
        "consensus": ConsensusMechanism.POS,
        "finality_type": SettlementFinality.ECONOMIC,
        "validator_count": 100,
        "nakamoto_coefficient": 5,
        "top_10_stake_pct": 55.0,
        "finality_time_seconds": 2.0,
        "tps_average": 65.0,
        "tps_peak": 7000.0,
        "uptime_30d_pct": 99.9,
        "major_incidents_12m": 0,
        "has_bug_bounty": True,
        "audit_count": 30,
        "time_since_last_upgrade_days": 45,
        "total_staked_usd": 3_000_000_000,
        "slashing_enabled": True,
    },
    "avalanche": {
        "consensus": ConsensusMechanism.POS,
        "finality_type": SettlementFinality.DETERMINISTIC,
        "validator_count": 1200,
        "nakamoto_coefficient": 26,
        "top_10_stake_pct": 30.0,
        "finality_time_seconds": 1.0,
        "tps_average": 4500.0,
        "tps_peak": 6000.0,
        "uptime_30d_pct": 99.9,
        "major_incidents_12m": 0,
        "has_bug_bounty": True,
        "audit_count": 25,
        "time_since_last_upgrade_days": 60,
        "total_staked_usd": 8_000_000_000,
        "slashing_enabled": True,
    },
    "bnb_chain": {
        "consensus": ConsensusMechanism.DPOS,
        "finality_type": SettlementFinality.DETERMINISTIC,
        "validator_count": 21,
        "nakamoto_coefficient": 7,
        "top_10_stake_pct": 70.0,
        "finality_time_seconds": 3.0,
        "tps_average": 100.0,
        "tps_peak": 2000.0,
        "uptime_30d_pct": 99.95,
        "major_incidents_12m": 1,
        "has_bug_bounty": True,
        "audit_count": 15,
        "time_since_last_upgrade_days": 30,
        "total_staked_usd": 5_000_000_000,
        "slashing_enabled": True,
    },
    "tron": {
        "consensus": ConsensusMechanism.DPOS,
        "finality_type": SettlementFinality.DETERMINISTIC,
        "validator_count": 27,
        "nakamoto_coefficient": 9,
        "top_10_stake_pct": 65.0,
        "finality_time_seconds": 3.0,
        "tps_average": 2000.0,
        "tps_peak": 10000.0,
        "uptime_30d_pct": 99.9,
        "major_incidents_12m": 0,
        "has_bug_bounty": True,
        "audit_count": 10,
        "time_since_last_upgrade_days": 90,
        "total_staked_usd": 10_000_000_000,
        "slashing_enabled": False,
    },
}
